/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#002113",
        "background": "#f4f6fa",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#10b981",
        "surface-container-highest": "#e5e7eb",
        "on-secondary-fixed": "#2a1700",
        "secondary-fixed": "#ffddb8",
        "surface-container-low": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#f9fafb",
        "primary-fixed": "#6ffbbe",
        "secondary-container": "#ee9800",
        "on-error": "#ffffff",
        "inverse-primary": "#006c49",
        "tertiary-container": "#fee2e2",
        "surface-bright": "#ffffff",
        "on-error-container": "#7f1d1d",
        "inverse-on-surface": "#2c3039",
        "on-tertiary-fixed-variant": "#930013",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-variant": "#e5e7eb",
        "inverse-surface": "#1a1f36",
        "primary": "#10b981",
        "surface": "#ffffff",
        "outline-variant": "#d1d5db",
        "surface-container": "#f3f4f6",
        "secondary-fixed-dim": "#ffb95f",
        "tertiary-fixed": "#ffdad7",
        "outline": "#9ca3af",
        "on-primary-container": "#065f46",
        "surface-dim": "#f3f4f6",
        "primary-container": "#d1fae5",
        "on-background": "#1a1f36",
        "on-tertiary-container": "#991b1b",
        "error-container": "#fee2e2",
        "tertiary": "#f43f5e",
        "on-surface": "#1a1f36",
        "surface-tint": "#10b981",
        "on-secondary-container": "#92400e",
        "on-tertiary-fixed": "#410004",
        "on-primary-fixed-variant": "#005236",
        "secondary": "#f59e0b",
        "on-secondary-fixed-variant": "#653e00",
        "on-surface-variant": "#6b7280",
        "error": "#ef4444",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-xl": "1.5rem",
        "gutter-desktop": "1rem",
        "margin-desktop": "1.5rem",
        "space-lg": "1rem",
        "space-xs": "0.25rem",
        "gutter-mobile": "0.5rem",
        "space-2xs": "0.125rem",
        "space-md": "0.75rem",
        "margin-mobile": "0.75rem",
        "space-2xl": "2rem"
      },
      fontFamily: {
        "telemetry-data": ["'JetBrains Mono'", "monospace"],
        "headline-xl": ["'Inter'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "body-sm": ["'Inter'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "headline-lg": ["'Inter'", "sans-serif"],
        "label-caps": ["'JetBrains Mono'", "monospace"],
        "metric-display-lg": ["'JetBrains Mono'", "monospace"],
        "metric-display-md": ["'JetBrains Mono'", "monospace"],
        "headline-sm": ["'Inter'", "sans-serif"],
        "headline-xl-mobile": ["'Inter'", "sans-serif"]
      },
      fontSize: {
        "telemetry-data": ["0.8125rem", { lineHeight: "1rem", letterSpacing: "0em", fontWeight: "500" }],
        "headline-xl": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-caps": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.08em", fontWeight: "600" }],
        "metric-display-lg": ["2rem", { lineHeight: "2.25rem", letterSpacing: "-0.03em", fontWeight: "700" }],
        "metric-display-md": ["1.25rem", { lineHeight: "1.5rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
}
